Repository OpenZWave/open-zwave, pull requests merged in 2018-07, with the labels that each got.

#1545 Renamed thermofloor z-trm2 config file following docs specs
  config/manufacturer_specific.xml
  config/thermofloor/heatit033.xml
  distfiles.mk
Labels: ConfigUpdate, NotReady

#1557 Support for Qubino 3-phase meter
  config/manufacturer_specific.xml
  config/qubino/ZMNHXDx.xml
  distfiles.mk
Labels: ConfigUpdate

#1550 support building on SmartOS
  cpp/build/Makefile
  cpp/examples/MinOZW/Makefile
  cpp/hidapi/libusb/hid.c
  cpp/src/platform/unix/SerialControllerImpl.cpp
Labels: enhancement

#1473 Allow build with newer Visual Studio
  cpp/build/winRT/vs2015/OpenZWave.vcxproj
  cpp/build/windows/vs2010/OpenZWave.vcxproj
Labels: bug

#1516 Make HID support optional (and disabled by default)
  cpp/build/Makefile
  cpp/build/libopenzwave.pc.in
  cpp/build/support.mk
  cpp/src/Driver.cpp
  cpp/src/platform/HidController.cpp
  cpp/src/platform/unix/SerialControllerImpl.cpp
Labels: enhancement
