Repository OpenZWave/open-zwave, pull requests merged in 2018-10, with the labels that each got.

#1612 Fix GetLabel for values
  cpp/src/Localization.cpp
  cpp/src/Localization.h
  cpp/src/value_classes/Value.cpp
Labels: bug

#1606 Fix broken build process for macOS
  cpp/build/Makefile
  cpp/build/support.mk
  cpp/examples/MinOZW/Makefile
Labels: bug

#1567 GR Multichannel Switches
  .gitignore
  ChangeLog
  config/gr/grb3.xml
  config/manufacturer_specific.xml
  cpp/src/command_classes/CommandClass.cpp
  cpp/src/command_classes/CommandClass.h
  cpp/src/command_classes/SensorMultilevel.cpp
Labels: enhancement

#1322 Support switch multilevel v4
  cpp/src/command_classes/SwitchMultilevel.cpp
Labels: CCNotCompliant, enhancement

#1580 Remove unused variables causing compilation errors on FreeBSD
  cpp/src/Group.cpp
  cpp/src/Group.h
  cpp/src/value_classes/ValueBool.cpp
  cpp/src/value_classes/ValueBool.h
  cpp/src/value_classes/ValueByte.cpp
  cpp/src/value_classes/ValueByte.h
  cpp/src/value_classes/ValueInt.cpp
  cpp/src/value_classes/ValueInt.h
  cpp/src/value_classes/ValueList.cpp
  cpp/src/value_classes/ValueList.h
  cpp/src/value_classes/ValueShort.cpp
  cpp/src/value_classes/ValueShort.h
Labels: bug

#1558 Simple AV command class and Remotec ZXT-310 #2
  config/manufacturer_specific.xml
  config/remotec/zxt-310.xml
  cpp/build/windows/vs2008/OpenZWave.vcproj
  cpp/build/windows/vs2010/OpenZWave.vcxproj
  cpp/build/windows/vs2010/OpenZWave.vcxproj.filters
  cpp/src/Node.cpp
  cpp/src/command_classes/CommandClasses.cpp
  cpp/src/command_classes/SimpleAV.cpp
  cpp/src/command_classes/SimpleAV.h
  cpp/src/command_classes/SimpleAVCommandItem.cpp
  cpp/src/command_classes/SimpleAVCommandItem.h
Labels: NotReady, PendingFeedback, enhancement
