Repository OpenZWave/open-zwave, pull requests merged in 2019-03, with the labels that each got.

#1721 Support for the Heltun HE-ZW-THERM-FL2 Heating Thermostat
  config/heltun/he-zw-therm-fl2.xml
  config/manufacturer_specific.xml
Labels: ConfigUpdate, NotReady

#1722 Update Neo CoolCam NAS-WR01ZE
  config/manufacturer_specific.xml
  config/shenzen_neo/nas-wr01ze.xml
Labels: ConfigUpdate, NotReady

#1723 Create nas-wr01ze.xml
  config/shenzen_neo/nas-wr01ze.xml
Labels: ConfigUpdate, duplicate

#1734 philio relay pan05 ru
  config/manufacturer_specific.xml
  config/philio/pan05.xml
Labels: ConfigUpdate, NotReady

#1729 Updated support for Aeotec NanoMote Quad
  config/aeotec/zwa003.xml
Labels: ConfigUpdate, PendingFeedback

#1750 Added useDestAsSource parameter in xml to use destination endpoint as…
  config/device_configuration.xsd
  config/greenwave/powernode6.xml
  cpp/src/command_classes/MultiInstance.cpp
  cpp/src/command_classes/MultiInstance.h
Labels: bug
