Repository OpenZWave/open-zwave, pull requests merged in 2019-07, with the labels that each got.

#1864 Add Zooz ZEN25 to list of devices in manufacturer_specfic.xml
  config/manufacturer_specific.xml
Labels: ConfigUpdate

#1869 Added Fibaro FGWDS221 Walli Double Switch
  config/fibaro/fgwds221.xml
  config/manufacturer_specific.xml
  cpp/build/testconfigversions.cfg
Labels: ConfigUpdate, NotReady, PendingFeedback

#1853 Create MHP220.xml
  config/images/mcohome/mhp220.png
  config/manufacturer_specific.xml
  config/mcohome/MHP220.xml
  cpp/build/testconfigversions.cfg
Labels: ConfigUpdate, NotReady, PendingFeedback

#1876 Change Interview Order to ensure we have the CC Version
  cpp/src/Node.cpp
  cpp/src/Node.h
  cpp/src/command_classes/CommandClass.cpp
  cpp/src/command_classes/CommandClass.h
  cpp/src/command_classes/MultiInstance.cpp
  cpp/src/command_classes/ThermostatSetpoint.cpp
  cpp/src/command_classes/ThermostatSetpoint.h
  cpp/src/command_classes/Version.cpp
  distfiles.mk
Labels: bug
