Repository OpenZWave/open-zwave, pull requests merged in 2019-12, with the labels that each got.

#2023 Fix comparison uint8 with -1, also test if controller node is 0.
  cpp/src/Driver.cpp
Labels: bug

#2025 Fix comparison uint8 with -1, also test if controller node is 0.
  cpp/src/Driver.cpp
Labels: bug

#2026 Make flock(m_hSerialController... actually do something
  cpp/src/platform/unix/SerialControllerImpl.cpp
Labels: enhancement

#2010 Make set after get optional - Fixed version
  config/device_configuration.xsd
  cpp/src/CompatOptionManager.cpp
  cpp/src/CompatOptionManager.h
  cpp/src/command_classes/CommandClass.cpp
  cpp/src/value_classes/Value.cpp
  cpp/src/value_classes/Value.h
  cpp/src/value_classes/ValueStore.cpp
Labels: PendingFeedback, enhancement

#2034 Call CheckCompletedNodeQueries in MoveMessagesToWakeUpQueue
  cpp/src/Driver.cpp
Labels: bug

#2050 Add fibaro flood sensor
  config/manufacturer_specific.xml
  cpp/build/testconfigversions.cfg
  distfiles.mk
Labels: ConfigUpdate
