Repository OpenZWave/open-zwave, pull requests merged in 2020-02, with the labels that each got.

#2101 Potential Fix for #2099 - Git Versions dont always work
  cpp/build/Makefile
  cpp/build/support.mk
  dist/openzwave.spec
Labels: enhancement

#2104 Refactor Interview Orders
  config/aeotec/zw162.xml
  cpp/build/testconfigversions.cfg
  cpp/examples/MinOZW/Main.cpp
  cpp/src/Driver.cpp
  cpp/src/Node.cpp
  cpp/src/Node.h
  cpp/src/Notification.cpp
  cpp/src/command_classes/Alarm.cpp
  cpp/src/command_classes/Association.h
  cpp/src/command_classes/AssociationCommandConfiguration.h
  cpp/src/command_classes/Basic.cpp
  cpp/src/command_classes/Battery.h
  cpp/src/command_classes/CRC16Encap.h
  cpp/src/command_classes/CentralScene.cpp
  cpp/src/command_classes/CommandClass.cpp
  cpp/src/command_classes/CommandClass.h
  cpp/src/command_classes/ControllerReplication.h
  cpp/src/command_classes/DeviceResetLocally.h
  cpp/src/command_classes/Language.h
  cpp/src/command_classes/ManufacturerSpecific.cpp
  cpp/src/command_classes/ManufacturerSpecific.h
  cpp/src/command_classes/MultiChannelAssociation.h
  cpp/src/command_classes/MultiInstance.cpp
  cpp/src/command_classes/MultiInstance.h
  cpp/src/command_classes/NodeNaming.h
  cpp/src/command_classes/Security.cpp
  cpp/src/command_classes/Security.h
  cpp/src/command_classes/SoundSwitch.cpp
  cpp/src/command_classes/ThermostatMode.cpp
  cpp/src/command_classes/ThermostatMode.h
  cpp/src/command_classes/ThermostatSetpoint.cpp
  cpp/src/command_classes/ThermostatSetpoint.h
  cpp/src/command_classes/Version.cpp
  cpp/src/command_classes/Version.h
  cpp/src/command_classes/WakeUp.cpp
  cpp/src/command_classes/WakeUp.h
  cpp/src/command_classes/ZWavePlusInfo.cpp
  dist/openzwave.spec
Labels: bug, enhancement

#2109 Fix type in Localization.xml
  config/Localization.xml
Labels: ConfigUpdate

#2100 Update manufacturer_specific.xml
  config/manufacturer_specific.xml
Labels: ConfigUpdate

#2076 CT32 thermostat config file updates
  config/2gig/ct32.xml
  cpp/build/testconfigversions.cfg
Labels: CCNotCompliant, ConfigUpdate

#2105 Added Haozee PIR Motion Sensor (Z52NAS-PD02Z)
  config/manufacturer_specific.xml
  cpp/build/testconfigversions.cfg
  distfiles.mk
Labels: PendingFeedback

#2124 Qubino ZMNHHDx Mini Dimmer: fix value type of config parameter 65
  config/qubino/ZMNHHDx.xml
  cpp/build/testconfigversions.cfg
Labels: ConfigUpdate

#2122 Added Widom devices: Double switch, Smart Plug, Smart Dimmer, Roller Shutter
  config/images/widom/DRY.png
  config/images/widom/UMS2.png
  config/images/widom/WDS2.png
  config/images/widom/WSP.png
  config/images/widom/WTED.png
  config/manufacturer_specific.xml
  config/widom/DRY.xml
  config/widom/UMS2.xml
  config/widom/WDS2.xml
  config/widom/WSP.xml
  config/widom/WTED.xml
  cpp/build/testconfigversions.cfg
  distfiles.mk
Labels: ConfigUpdate

#2121 Bump version
  config/aeotec/zw141.xml
  config/manufacturer_specific.xml
  cpp/build/testconfigversions.cfg
Labels: ConfigUpdate

#2118 Add new Zooz products: ZEN16, ZEN30 and ZEN31
  config/images/zooz/zen16.png
  config/images/zooz/zen30.png
  config/images/zooz/zen31.png
  config/manufacturer_specific.xml
  config/zooz/zen16.xml
  config/zooz/zen30.xml
  config/zooz/zen31.xml
  cpp/build/testconfigversions.cfg
  distfiles.mk
Labels: ConfigUpdate

#2111 Fix particulate matter spelling
  config/SensorMultiLevelCCTypes.xml
Labels: ConfigUpdate

#2110 Fix particulate matter spelling
  config/Localization.xml
Labels: ConfigUpdate
