Repository OpenZWave/open-zwave, pull requests merged in 2020-04, with the labels that each got.

#2170 Fix snprintf truncated value
  cpp/src/command_classes/Configuration.cpp
Labels: bug

#2172 Fix for #1588
  cpp/src/command_classes/Color.cpp
Labels: bug

#2176 Add missing option for ZW162 (Aeotec Doorbell 6)
  config/aeotec/zw162.xml
Labels: ConfigUpdate

#2178 Termux / Android compatibility
  cpp/src/command_classes/Configuration.cpp
  cpp/src/platform/unix/EventImpl.cpp
  cpp/src/platform/unix/SerialControllerImpl.cpp
  cpp/src/platform/unix/ThreadImpl.cpp
  cpp/src/platform/unix/android.h
Labels: enhancement
