Repository OpenZWave/open-zwave, pull requests merged in 2020-07, with the labels that each got.

#2279 Adding connecthome/CH-201 configuration
  config/connecthome/ch-201.xml
  config/images/connecthome/CH_201.png
  config/manufacturer_specific.xml
  cpp/build/testconfigversions.cfg
  distfiles.mk
Labels: ConfigUpdate

#2283 Add support For Ge 12720
  config/ge/12720.xml
  config/manufacturer_specific.xml
Labels: ConfigUpdate

#2288 Added support for zwn-rsm2-plus
  config/enerwave/zwnrsm2plus.xml
  config/images/enerwave/zwnrsm2plus.png
  config/manufacturer_specific.xml
  cpp/build/testconfigversions.cfg
  dist/openzwave.spec
  distfiles.mk
Labels: ConfigUpdate, NotReady, PendingFeedback

#2291 add q-light zerodim, zerodim 2 pol and puck
  config/images/q-light/q-light_puck.png
  config/images/q-light/q-light_zerodim.png
  config/images/q-light/q-light_zerodim_2pol.png
  config/manufacturer_specific.xml
  config/q-light/q-light_puck.xml
  config/q-light/q-light_zerodim.xml
  config/q-light/q-light_zerodim_2pol.xml
  cpp/build/testconfigversions.cfg
Labels: ConfigUpdate, NotReady, PendingFeedback

#2294 Added support for WT00Z5-1
  config/images/linear/WT00Z5-1.png
  config/linear/WT00Z5-1.xml
  config/manufacturer_specific.xml
  cpp/build/testconfigversions.cfg
  distfiles.mk
Labels: ConfigUpdate

#2266 Adding in Fibaro Motion Sensor
  config/fibaro/fgmszw5.xml
  config/manufacturer_specific.xml
  cpp/build/testconfigversions.cfg
Labels: ConfigUpdate, PendingFeedback

#2274 Create Leviton DZPA1.xml and image, Revise DZ15S and Image
  config/images/leviton/dz15s.png
  config/images/leviton/dzpa1.png
  config/leviton/dz15s.xml
  config/leviton/dzpa1.xml
  config/manufacturer_specific.xml
Labels: ConfigUpdate, PendingFeedback

#2278 Add Support for Leviton VRPA1
  config/images/leviton/vrpa1.png
  config/leviton/vrpa1.xml
  config/manufacturer_specific.xml
  cpp/build/testconfigversions.cfg
Labels: ConfigUpdate

#2281 Add support for Heatit Z-Water TF 20a
  config/images/thermofloor/heatit20a.png
  config/manufacturer_specific.xml
  config/thermofloor/heatit20a.xml
  cpp/build/testconfigversions.cfg
  distfiles.mk
Labels: ConfigUpdate

#2295 Add support for Inovelli lzw36 fan-switch combo
  config/inovelli/lzw36.xml
  config/manufacturer_specific.xml
Labels: ConfigUpdate, NotReady

#2296 Added Nexia TH100NX Temperature and Humidity Sensor
  config/images/nexia/th100nx.png
  config/manufacturer_specific.xml
  config/nexia/th100nx.xml
  cpp/build/testconfigversions.cfg
  distfiles.mk
Labels: ConfigUpdate

#2297 [FIX] Smartcode.xml TriggerRefreshValue idx 0=>6
  config/kwikset/smartcode.xml
Labels: ConfigUpdate

#2302 add support for GE 14298 S2 Outdoor Smart Switch
  config/ge/14298.xml
  config/images/ge/14298.png
  config/manufacturer_specific.xml
Labels: ConfigUpdate

#2307 Add support for FGDW-002 US model and DMEX1 extender
  config/dome/dmex1.xml
  config/fibaro/fgdw2.xml
  config/images/dome/dmex1.png
  config/manufacturer_specific.xml
Labels: ConfigUpdate

#2309 Added WNK SIR1P and GE 46204
  config/ge/46204-dimmer-toggle.xml
  config/images/ge/46204-dimmer-toggle.png
  config/images/wink/wnk-sir1p.png
  config/manufacturer_specific.xml
  config/wink/wnk-sir1p.xml
  cpp/build/testconfigversions.cfg
Labels: ConfigUpdate

#2316 Fix TriggerRefreshValue for Schlage BE468 locks
  config/schlage/BE468.xml
Labels: ConfigUpdate
