Repository OpenZWave/open-zwave, pull requests merged in 2020-11, with the labels that each got.

#2330 Initial support for Leviton VRPD3-1LW Vizia RF+ 300 Watt Scene Capabl…
  config/images/leviton/vrpd3.png
  config/leviton/vrpd3.xml
  config/manufacturer_specific.xml
Labels: ConfigUpdate

#2332 Several Config Parameter Fixes for LZW30, LZW30-SN, LZW31, LZW31-SN, LZW36
  config/inovelli/lzw30-sn.xml
  config/inovelli/lzw30.xml
  config/inovelli/lzw31-sn.xml
  config/inovelli/lzw31.xml
  config/inovelli/lzw36.xml
Labels: ConfigUpdate

#2318 Add manufacturer EcoDim and their LED Dimmer
  config/ecodim/0.7.xml
  config/images/ecodim/0.7.jpg
  config/manufacturer_specific.xml
  cpp/build/testconfigversions.cfg
Labels: ConfigUpdate, NotReady, PendingFeedback

#2343 Fixed iterator deletion
  cpp/src/Scene.cpp
  cpp/src/command_classes/WakeUp.cpp
  cpp/src/platform/HttpClient.cpp
  cpp/src/value_classes/ValueStore.cpp
Labels: bug

#2344 Add support for ls03ch
  config/images/shenzen_neo/ls03ch.jpg
  config/manufacturer_specific.xml
  config/shenzen_neo/ls03ch.xml
Labels: ConfigUpdate

#2348 Add support for Honeywell ZW1002 Outlet
  config/honeywell/39349-ZW1002.xml
  config/images/honeywell/39349-ZW1002.png
  config/manufacturer_specific.xml
Labels: ConfigUpdate

#2350 added FirstAlert ZSMOKE config
  config/firstalert/zsmoke.xml
  config/images/firstalert/zsmoke.png
  config/manufacturer_specific.xml
  cpp/build/testconfigversions.cfg
Labels: ConfigUpdate

#2357 Add New Device from TechniSat (Dimmer)
  config/images/technisat/03009497.png
  config/manufacturer_specific.xml
  config/technisat/03009497.xml
  cpp/build/testconfigversions.cfg
  distfiles.mk
Labels: ConfigUpdate

#2334 Added support for Simon 100 iO Roller Blind 10002080_13X.
  config/images/simon/10002080-13X.png
  config/manufacturer_specific.xml
  config/simon/10002080-13X.xml
Labels: ConfigUpdate, NotReady, PendingFeedback

#2352 Add initial support for Sunricher ZV2835RAC
  config/images/sunricher/zv2835rac.png
  config/manufacturer_specific.xml
  config/sunricher/zv2835rac.xml
Labels: ConfigUpdate

#2370 SwitchBinary CC to include payload length before assuming V2 message content
  cpp/src/command_classes/Basic.cpp
  cpp/src/command_classes/SwitchBinary.cpp
Labels: bug

#2422 Added Fibaro FGS-224
  config/fibaro/fgs224.xml
  config/images/fibaro/fgs224.png
  config/manufacturer_specific.xml
Labels: ConfigUpdate

#2413 BE469ZP User index="6" update
  config/schlage/BE469ZP.xml
Labels: ConfigUpdate, NotReady, PendingFeedback

#2423 Update manufacturer_specific.xml
  config/manufacturer_specific.xml
Labels: ConfigUpdate

#2432 Add support for NEO Siren Australia
  config/manufacturer_specific.xml
Labels: ConfigUpdate

#2443 Add support for GE/Jasco 26932 In-Wall Smart Motion Dimmer
  config/ge/26932-motion-dimmer.xml
  config/manufacturer_specific.xml
Labels: ConfigUpdate

#2444 Update Cooper RF9540-N device
  config/cooper/RF9540-N.xml
Labels: ConfigUpdate

#2368 Create heatitz4.xml
  config/thermofloor/heatitz4.xml
Labels: ConfigUpdate, NotReady, PendingFeedback

#2311 New manufacturer files for ARZ Solar and ZRH12 Fakro devices.
  config/fakro/arzsolar.xml
  config/fakro/zrh12.xml
  config/manufacturer_specific.xml
Labels: ConfigUpdate, NotReady, PendingFeedback

#2056 Fixed a problem with lifeline group 1.1
  config/qubino/ZMNHCDx.xml
Labels: ConfigUpdate, PendingFeedback
