Repository OpenZWave/open-zwave, pull requests merged in 2020-03, with the labels that each got.

#2136 Add support for Popp device
  config/images/popp/701202.png
  config/manufacturer_specific.xml
  config/popp/701202.xml
Labels: ConfigUpdate

#2135 Add honeywell 39351-ZW3010
  config/honeywell/39351-ZW3010.xml
  config/manufacturer_specific.xml
Labels: ConfigUpdate

#2138 do not sychronize a BASIC set/report when Get is not supported
  cpp/src/command_classes/SensorBinary.cpp
Labels: enhancement

#2077 Additional Inovelli device support
  config/images/inovelli/lzw31-sn.png
  config/images/inovelli/lzw31.png
  config/images/inovelli/lzw40.png
  config/images/inovelli/lzw41.png
  config/images/inovelli/lzw42.png
  config/inovelli/lzw31-sn.xml
  config/inovelli/lzw31.xml
  config/inovelli/lzw40.xml
  config/inovelli/lzw41.xml
  config/inovelli/lzw42.xml
  config/manufacturer_specific.xml
  cpp/build/testconfigversions.cfg
Labels: ConfigUpdate, NotReady, PendingFeedback

#2150 Implement Configuration CommandClass Version 4
  cpp/src/Driver.cpp
  cpp/src/Driver.h
  cpp/src/Notification.h
  cpp/src/ValueIDIndexesDefines.def
  cpp/src/ValueIDIndexesDefines.h
  cpp/src/command_classes/ApplicationStatus.cpp
  cpp/src/command_classes/Configuration.cpp
  cpp/src/command_classes/Configuration.h
  cpp/src/value_classes/Value.h
  dist/openzwave.spec
Labels: enhancement

#2151 Fix maybe-uninitialized warning
  cpp/src/command_classes/Configuration.cpp
Labels: bug

#2153 added support for new eurotronic sensors
  config/eurotronic/eur_airquality.xml
  config/eurotronic/eur_temphumin.xml
  config/images/eurotronic/eur_airquality.png
  config/images/eurotronic/eur_temphumid.png
  config/manufacturer_specific.xml
Labels: ConfigUpdate, NotReady

#2157 Adds North American ID information for Aeotec ZW164-A
  config/aeotec/zw164.xml
  config/manufacturer_specific.xml
  cpp/build/testconfigversions.cfg
Labels: ConfigUpdate

#2163 Add Honeywell 39348-ZW4005 In-Wall Smart Switch
  config/honeywell/39348-ZW4005.xml
  config/images/honeywell/39348-ZW4005.png
  config/manufacturer_specific.xml
  cpp/build/testconfigversions.cfg
  distfiles.mk
Labels: ConfigUpdate

#1906 Adding ZDB5100 Matrix Switch
  config/images/logicsoft/ZDB5100.png
  config/logicsoft/ZDB5100.xml
  config/manufacturer_specific.xml
  cpp/build/testconfigversions.cfg
  distfiles.mk
Labels: ConfigUpdate, NotReady

#2168 Rename Serial Version to Firmware Version and add Communication and Chip Version
  cpp/src/Driver.cpp
  cpp/src/Driver.h
Labels: enhancement

#2167 Adding the configuration file for Qubino Luxy Switch (ZMNKAD)
  config/manufacturer_specific.xml
  config/qubino/ZMNHQDx.xml
  config/qubino/ZMNKADx.xml
  cpp/build/testconfigversions.cfg
Labels: ConfigUpdate

#2161 parameter 12 has wrong default in description
  config/fibaro/fgsd002.xml
Labels: ConfigUpdate, NotReady
