Repository OpenZWave/open-zwave, pull requests merged in 2020-06, with the labels that each got.

#2247 Update BE469.xml TriggerRefreshValue
  config/manufacturer_specific.xml
  config/schlage/BE469.xml
Labels: ConfigUpdate

#2232 Updates for Zooz Zen27 and ZSE29
  config/zooz/zen27.xml
  config/zooz/zse29.xml
Labels: ConfigUpdate

#2231 Add config for Honeywell ZW4106 Plug-in Smart Switch
  config/honeywell/39449-ZW4106.xml
  config/images/honeywell/39449-ZW4106.png
  config/manufacturer_specific.xml
  cpp/build/testconfigversions.cfg
Labels: ConfigUpdate

#2230 Adds config for devolo Home Control Dimmer FM MT2760
  config/devolo/mt2760.xml
  config/images/devolo/mt2760.png
  config/manufacturer_specific.xml
  cpp/build/testconfigversions.cfg
  distfiles.mk
Labels: ConfigUpdate

#2245 Adding support for LZW60 Inovelli Device
  config/images/inovelli/lzw60.png
  config/inovelli/lzw60.xml
  config/manufacturer_specific.xml
Labels: ConfigUpdate, NotReady, PendingFeedback

#2252 New Devices from TechniSat (shutter and single-switch)
  config/images/technisat/03009496.png
  config/images/technisat/03009499.png
  config/manufacturer_specific.xml
  config/technisat/03009496.xml
  config/technisat/03009499.xml
  cpp/build/testconfigversions.cfg
  distfiles.mk
Labels: ConfigUpdate

#2254 Update config-template.xml
  config/config-template.xml
Labels: enhancement

#2256 fixed kwikset 914c alarm message index for refresh
  config/kwikset/914c.xml
  cpp/build/testconfigversions.cfg
Labels: ConfigUpdate

#2250 Update for Zooz ZEN21v3, add Zooz ZEN24v2 config
  config/images/zooz/zen21v3.png
  config/images/zooz/zen24v2.png
  config/manufacturer_specific.xml
  config/zooz/zen21v3.xml
  config/zooz/zen24v2.xml
Labels: ConfigUpdate

#2260 Fix YRD446 alarm message index for refresh
  config/assa_abloy/TouchDeadbolt.xml
Labels: ConfigUpdate

#2261 Update ZEN21v3 parameter 12 description
  config/zooz/zen21v3.xml
Labels: ConfigUpdate

#2263 add Zooz ZEN23v3 config
  config/images/zooz/zen23v3.png
  config/zooz/zen23v3.xml
Labels: ConfigUpdate

#2272 Add VerifyChange to Homeseer HS-WD100+ to resolve out-of-sync state
  config/homeseer/hs-wd100plus.xml
  cpp/build/testconfigversions.cfg
Labels: ConfigUpdate

#2240 Added GE Z-Wave Direct-Wire Outdoor/Indoor Smart Switch
  config/ge/14285.xml
  config/images/ge/14285.png
  config/manufacturer_specific.xml
  cpp/build/testconfigversions.cfg
Labels: ConfigUpdate, NotReady, PendingFeedback

#2265 Add support for the WNK-MOT1 Wink Motion Sensor
  config/images/wink/wnk-mot1.png
  config/manufacturer_specific.xml
  config/wink/wnk-mot1.xml
  cpp/build/testconfigversions.cfg
  distfiles.mk
Labels: ConfigUpdate, PendingFeedback

#2273 Update for revised Zooz ZEN23 config
  config/manufacturer_specific.xml
Labels: ConfigUpdate

#2271 Add Support For Smartcode 888 Deadbolt - 888.xml
  config/images/kwikset/888.png
  config/kwikset/888.xml
  config/manufacturer_specific.xml
Labels: ConfigUpdate, PendingFeedback

#2277 Fix YRD216 alarm message index for value refresh
  config/assa_abloy/PushButtonDeadbolt.xml
Labels: ConfigUpdate
